const movies = [
  {
    "id": 1,
    "title": "Inception",
    "trailerURL": "https://youtu.be/YoHD9XEInc0",
    "posterURL": "https://image.tmdb.org/t/p/original/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    "rating": 8.8,
    "description": "A skilled thief who steals secrets by entering people’s dreams is tasked with planting an idea in someone’s subconscious.",
    "budget": "160,000,000",
    "revenue": "829,895,144",
    "genres": ["Action","Sci-Fi","Thriller"],
    "releaseDate": "2010-07-15",
    "actors": ["Leonardo DiCaprio","Joseph Gordon-Levitt","Elliot Page","Tom Hardy","Ken Watanabe"],
    "director": "Christopher Nolan",
    "author": "Christopher Nolan"
  },
  {
    "id": 2,
    "title": "The Dark Knight",
    "trailerURL": "https://youtu.be/EXeTwQWrcwY",
    "posterURL": "https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    "rating": 9.0,
    "description": "Batman faces the Joker, who plunges Gotham into chaos while forcing Batman to confront his own moral code.",
    "budget": "185,000,000",
    "revenue": "1,004,558,444",
    "genres": ["Action","Crime","Drama"],
    "releaseDate": "2008-07-18",
    "actors": ["Christian Bale","Heath Ledger","Aaron Eckhart","Michael Caine","Maggie Gyllenhaal"],
    "director": "Christopher Nolan",
    "author": "Jonathan Nolan"
  },
  {
    "id": 3,
    "title": "The Shawshank Redemption",
    "trailerURL": "https://youtu.be/6hB3S9bIaco",
    "posterURL": "https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    "rating": 8.7,
    "description": "Two imprisoned men bond over years, finding hope and purpose despite harsh prison life.",
    "budget": "25,000,000",
    "revenue": "28,341,469",
    "genres": ["Drama","Crime"],
    "releaseDate": "1994-09-23",
    "actors": ["Tim Robbins","Morgan Freeman","Bob Gunton","William Sadler","Clancy Brown"],
    "director": "Frank Darabont",
    "author": "Stephen King"
  },
  {
    "id": 4,
    "title": "Fight Club",
    "trailerURL": "https://youtu.be/SUXWAEX2jlg",
    "posterURL": "https://image.tmdb.org/t/p/original/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg",
    "rating": 8.4,
    "description": "An insomniac white-collar worker forms an underground fight club with a soap salesman, changing both their lives.",
    "budget": "63,000,000",
    "revenue": "100,853,753",
    "genres": ["Drama"],
    "releaseDate": "1999-10-15",
    "actors": ["Brad Pitt","Edward Norton","Meat Loaf","Jared Leto","Helena Bonham Carter"],
    "director": "David Fincher",
    "author": "Chuck Palahniuk"
  },
  {
    "id": 5,
    "title": "Forrest Gump",
    "trailerURL": "https://youtu.be/bLvqoHBptjg",
    "posterURL": "https://image.tmdb.org/t/p/original/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
    "rating": 8.8,
    "description": "A man with a low IQ recounts the extraordinary events of his life while sitting at a bus stop.",
    "budget": "55,000,000",
    "revenue": "678,222,284",
    "genres": ["Drama","Romance"],
    "releaseDate": "1994-07-06",
    "actors": ["Tom Hanks","Robin Wright","Gary Sinise","Mykelti Williamson","Sally Field"],
    "director": "Robert Zemeckis",
    "author": "Winston Groom"
  },
  {
    "id": 6,
    "title": "The Lord of the Rings: The Return of the King",
    "trailerURL": "https://youtu.be/r5X-hFf6Bwo",
    "posterURL": "https://image.tmdb.org/t/p/original/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    "rating": 8.9,
    "description": "The final confrontation between the forces of good and evil fighting for control of Middle‑earth.",
    "budget": "94,000,000",
    "revenue": "1,146,030,912",
    "genres": ["Adventure","Fantasy","Action"],
    "releaseDate": "2003-12-17",
    "actors": ["Elijah Wood","Viggo Mortensen","Ian McKellen","Orlando Bloom","Sean Astin"],
    "director": "Peter Jackson",
    "author": "J.R.R. Tolkien"
  },
  {
    "id": 7,
    "title": "Interstellar",
    "trailerURL": "https://youtu.be/zSWdZVtXT7E",
    "posterURL": "https://image.tmdb.org/t/p/original/81kzL9sx-3L._AC_SL1500_.jpg",
    "rating": 8.6,
    "description": "A team of explorers travels through a wormhole in space to ensure humanity’s survival.",
    "budget": "165,000,000",
    "revenue": "677,471,339",
    "genres": ["Adventure","Drama","Sci‑Fi"],
    "releaseDate": "2014-11-07",
    "actors": ["Matthew McConaughey","Anne Hathaway","Jessica Chastain","Michael Caine","Casey Affleck"],
    "director": "Christopher Nolan",
    "author": "Jonathan Nolan"
  },
  {
    "id": 8,
    "title": "Gladiator",
    "trailerURL": "https://youtu.be/owK1qxDselE",
    "posterURL": "https://image.tmdb.org/t/p/original/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    "rating": 8.5,
    "description": "A betrayed Roman general rises as a gladiator to seek revenge against the corrupt emperor.",
    "budget": "103,000,000",
    "revenue": "460,583,960",
    "genres": ["Action","Drama","Adventure"],
    "releaseDate": "2000-05-05",
    "actors": ["Russell Crowe","Joaquin Phoenix","Connie Nielsen","Oliver Reed","Derek Jacobi"],
    "director": "Ridley Scott",
    "author": "David Franzoni"
  },
  {
    "id": 9,
    "title": "The Matrix",
    "trailerURL": "https://youtu.be/vKQi3bBA1y8",
    "posterURL": "https://image.tmdb.org/t/p/original/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    "rating": 8.7,
    "description": "A hacker discovers reality is a simulation and joins rebels to free humanity from machines.",
    "budget": "63,000,000",
    "revenue": "463,517,383",
    "genres": ["Action","Sci‑Fi"],
    "releaseDate": "1999-03-31",
    "actors": ["Keanu Reeves","Laurence Fishburne","Carrie‑Anne Moss","Hugo Weaving","Joe Pantoliano"],
    "director": "The Wachowskis",
    "author": "The Wachowskis"
  },
  {
    "id": 10,
    "title": "Avatar",
    "trailerURL": "https://youtu.be/5PSNL1qE6VY",
    "posterURL": "https://image.tmdb.org/t/p/original/6EiRUJpuoeQPghrs3YNktfnqOVh.jpg",
    "rating": 7.8,
    "description": "On the alien world of Pandora, humans clash with indigenous Na’vi over resources and survival.",
    "budget": "237,000,000",
    "revenue": "2,847,246,203",
    "genres": ["Action","Adventure","Fantasy"],
    "releaseDate": "2009-12-18",
    "actors": ["Sam Worthington","Zoe Saldana","Sigourney Weaver","Stephen Lang","Michelle Rodriguez"],
    "director": "James Cameron",
    "author": "James Cameron"
  },
  {
    "id": 11,
    "title": "Titanic",
    "trailerURL": "https://youtu.be/kVrqfYjkTdQ",
    "posterURL": "https://image.tmdb.org/t/p/original/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    "rating": 7.9,
    "description": "A young couple falls in love aboard the ill‑fated RMS Titanic while tragedy unfolds.",
    "budget": "200,000,000",
    "revenue": "2,201,647,264",
    "genres": ["Drama","Romance"],
    "releaseDate": "1997-12-19",
    "actors": ["Leonardo DiCaprio","Kate Winslet","Billy Zane","Kathy Bates","Frances Fisher"],
    "director": "James Cameron",
    "author": "James Cameron"
  },
  {
    "id": 12,
    "title": "Jurassic Park",
    "trailerURL": "https://youtu.be/QWBKEmWWL38",
    "posterURL": "https://image.tmdb.org/t/p/original/fcikG74LY9H9y7AR2mkhyYcQWtv.jpg",
    "rating": 8.1,
    "description": "Scientists resurrect dinosaurs for a theme park, leading to chaos and survival battles.",
    "budget": "63,000,000",
    "revenue": "1,033,919,889",
    "genres": ["Action","Adventure","Sci‑Fi"],
    "releaseDate": "1993-06-11",
    "actors": ["Sam Neill","Laura Dern","Jeff Goldblum","Richard Attenborough","Bob Peck"],
    "director": "Steven Spielberg",
    "author": "Michael Crichton"
  },
  {
    "id": 13,
    "title": "The Lion King",
    "trailerURL": "https://youtu.be/7TavVZMewpY",
    "posterURL": "https://image.tmdb.org/t/p/original/sKCr78MXSLbx5kSyvMqVvXa9Bt2.jpg",
    "rating": 8.5,
    "description": "A young lion prince flees after his father’s death, later returning to claim his place in the Circle of Life.",
    "budget": "45,000,000",
    "revenue": "968,483,777",
    "genres": ["Animation","Adventure","Drama"],
    "releaseDate": "1994-06-24",
    "actors": ["Matthew Broderick","Jeremy Irons","James Earl Jones","Whoopi Goldberg","Nathan Lane"],
    "director": "Roger Allers & Rob Minkoff",
    "author": "Irene Mecchi"
  },
  {
    "id": 14,
    "title": "Back to the Future",
    "trailerURL": "https://youtu.be/qvsgGtivCgs",
    "posterURL": "https://image.tmdb.org/t/p/original/pTpxQB9kq2wXdZxMtNNFh18OZCB.jpg",
    "rating": 8.5,
    "description": "A teen is accidentally sent back in time, jeopardizing his parents’ future and struggling to fix history.",
    "budget": "19,000,000",
    "revenue": "389,113,867",
    "genres": ["Adventure","Comedy","Sci‑Fi"],
    "releaseDate": "1985-07-03",
    "actors": ["Michael J. Fox","Christopher Lloyd","Lea Thompson","Crispin Glover","Thomas F. Wilson"],
    "director": "Robert Zemeckis",
    "author": "Robert Zemeckis"
  },
  {
    "id": 15,
    "title": "Terminator 2: Judgment Day",
    "trailerURL": "https://youtu.be/eajuMYNYtuY",
    "posterURL": "https://image.tmdb.org/t/p/original/9Sw0gFzRm3FQIqvFa0b6O3KJ2hS.jpg",
    "rating": 8.5,
    "description": "A cyborg must protect a boy from a more advanced terminator from the future.",
    "budget": "102,000,000",
    "revenue": "520,881,154",
    "genres": ["Action","Sci‑Fi"],
    "releaseDate": "1991-07-03",
    "actors": ["Arnold Schwarzenegger","Linda Hamilton","Edward Furlong","Robert Patrick","Earl Boen"],
    "director": "James Cameron",
    "author": "James Cameron"
  },
  {
    "id": 16,
    "title": "Star Wars: Episode IV – A New Hope",
    "trailerURL": "https://youtu.be/vZ734NWnAHA",
    "posterURL": "https://image.tmdb.org/t/p/original/rqAEzIFw5cgI6Ii6fM7uVeFQXcQ.jpg",
    "rating": 8.6,
    "description": "A farm boy joins forces with rebels to save the galaxy from a tyrannical empire.",
    "budget": "11,000,000",
    "revenue": "775,398,007",
    "genres": ["Adventure","Sci‑Fi","Action"],
    "releaseDate": "1977-05-25",
    "actors": ["Mark Hamill","Harrison Ford","Carrie Fisher","Alec Guinness","Peter Cushing"],
    "director": "George Lucas",
    "author": "George Lucas"
  },
  {
"id": 17,
"title": "The Avengers",
"trailerURL": "https://youtu.be/eOrNdBpGMv8",
"posterURL": "https://image.tmdb.org/t/p/original/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
"rating": 8.0,
"description": "Earth's mightiest heroes assemble to stop the god Loki and his alien army from conquering Earth.",
"budget": "220,000,000",
"revenue": "1,518,812,988",
"genres": ["Action","Adventure","Sci-Fi"],
"releaseDate": "2012-05-04",
"actors": ["Robert Downey Jr.","Chris Evans","Scarlett Johansson","Mark Ruffalo","Chris Hemsworth"],
"director": "Joss Whedon",
"author": "Zak Penn"
},

{
"id": 18,
"title": "Iron Man",
"trailerURL": "https://youtu.be/8hYlB38asDY",
"posterURL": "https://image.tmdb.org/t/p/original/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
"rating": 7.9,
"description": "A billionaire inventor builds a powerful armored suit after escaping captivity and becomes the hero Iron Man.",
"budget": "140,000,000",
"revenue": "585,796,247",
"genres": ["Action","Sci-Fi"],
"releaseDate": "2008-05-02",
"actors": ["Robert Downey Jr.","Gwyneth Paltrow","Jeff Bridges","Terrence Howard","Clark Gregg"],
"director": "Jon Favreau",
"author": "Mark Fergus"
},

{
"id": 19,
"title": "Black Panther",
"trailerURL": "https://youtu.be/xjDjIWPwcPU",
"posterURL": "https://image.tmdb.org/t/p/original/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
"rating": 7.3,
"description": "The king of Wakanda must defend his nation and the powerful vibranium technology from enemies.",
"budget": "200,000,000",
"revenue": "1,347,597,973",
"genres": ["Action","Adventure"],
"releaseDate": "2018-02-16",
"actors": ["Chadwick Boseman","Michael B. Jordan","Lupita Nyong'o","Danai Gurira","Martin Freeman"],
"director": "Ryan Coogler",
"author": "Ryan Coogler"
},

{
"id": 20,
"title": "Doctor Strange",
"trailerURL": "https://youtu.be/HSzx-zryEgM",
"posterURL": "https://image.tmdb.org/t/p/original/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg",
"rating": 7.5,
"description": "A brilliant but arrogant surgeon discovers the hidden world of mystic arts after a life-changing accident.",
"budget": "165,000,000",
"revenue": "677,718,395",
"genres": ["Action","Fantasy"],
"releaseDate": "2016-11-04",
"actors": ["Benedict Cumberbatch","Rachel McAdams","Tilda Swinton","Chiwetel Ejiofor","Mads Mikkelsen"],
"director": "Scott Derrickson",
"author": "Jon Spaihts"
},

{
"id": 21,
"title": "Spider-Man: Homecoming",
"trailerURL": "https://youtu.be/U0D3AOldjMU",
"posterURL": "https://image.tmdb.org/t/p/original/kY2c7wKgOfQjvbqe7yVzLTYkxJO.jpg",
"rating": 7.4,
"description": "Peter Parker balances high school life while proving himself worthy as Spider-Man.",
"budget": "175,000,000",
"revenue": "880,166,924",
"genres": ["Action","Adventure"],
"releaseDate": "2017-07-07",
"actors": ["Tom Holland","Michael Keaton","Robert Downey Jr.","Zendaya","Marisa Tomei"],
"director": "Jon Watts",
"author": "Jonathan Goldstein"
},

{
"id": 22,
"title": "Joker",
"trailerURL": "https://youtu.be/zAGVQLHvwOY",
"posterURL": "https://image.tmdb.org/t/p/original/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
"rating": 8.4,
"description": "A struggling comedian descends into madness and becomes Gotham City's most infamous criminal.",
"budget": "55,000,000",
"revenue": "1,074,458,282",
"genres": ["Crime","Drama","Thriller"],
"releaseDate": "2019-10-04",
"actors": ["Joaquin Phoenix","Robert De Niro","Zazie Beetz","Frances Conroy","Brett Cullen"],
"director": "Todd Phillips",
"author": "Todd Phillips"
},

{
"id": 23,
"title": "The Social Network",
"trailerURL": "https://youtu.be/lB95KLmpLR4",
"posterURL": "https://image.tmdb.org/t/p/original/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
"rating": 7.7,
"description": "The story of the founding of Facebook and the legal battles that followed.",
"budget": "40,000,000",
"revenue": "224,920,315",
"genres": ["Drama","Biography"],
"releaseDate": "2010-10-01",
"actors": ["Jesse Eisenberg","Andrew Garfield","Justin Timberlake","Armie Hammer","Max Minghella"],
"director": "David Fincher",
"author": "Aaron Sorkin"
},

{
"id": 24,
"title": "The Wolf of Wall Street",
"trailerURL": "https://youtu.be/iszwuX1AK6A",
"posterURL": "https://image.tmdb.org/t/p/original/pWHf4khOloNVfCxscsXFj3jj6gP.jpg",
"rating": 8.2,
"description": "A stockbroker rises to immense wealth through corruption and fraud before facing the consequences.",
"budget": "100,000,000",
"revenue": "406,878,233",
"genres": ["Biography","Drama"],
"releaseDate": "2013-12-25",
"actors": ["Leonardo DiCaprio","Jonah Hill","Margot Robbie","Matthew McConaughey","Kyle Chandler"],
"director": "Martin Scorsese",
"author": "Terence Winter"
},

{
"id": 25,
"title": "The Silence of the Lambs",
"trailerURL": "https://youtu.be/W6Mm8Sbe__o",
"posterURL": "https://image.tmdb.org/t/p/original/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg",
"rating": 8.6,
"description": "An FBI trainee seeks help from a brilliant cannibalistic psychiatrist to catch a serial killer.",
"budget": "19,000,000",
"revenue": "272,742,922",
"genres": ["Thriller","Crime"],
"releaseDate": "1991-02-14",
"actors": ["Jodie Foster","Anthony Hopkins","Scott Glenn","Ted Levine","Anthony Heald"],
"director": "Jonathan Demme",
"author": "Thomas Harris"
},

{
"id": 26,
"title": "The Godfather",
"trailerURL": "https://youtu.be/sY1S34973zA",
"posterURL": "https://image.tmdb.org/t/p/original/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
"rating": 9.2,
"description": "The aging patriarch of a powerful crime family transfers control of his empire to his reluctant son.",
"budget": "6,000,000",
"revenue": "246,120,974",
"genres": ["Crime","Drama"],
"releaseDate": "1972-03-24",
"actors": ["Marlon Brando","Al Pacino","James Caan","Robert Duvall","Diane Keaton"],
"director": "Francis Ford Coppola",
"author": "Mario Puzo"
},

{
"id": 27,
"title": "The Godfather Part II",
"trailerURL": "https://youtu.be/9O1Iy9od7-A",
"posterURL": "https://image.tmdb.org/t/p/original/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
"rating": 9.0,
"description": "The early life of Vito Corleone is contrasted with his son Michael's expansion of the family crime empire.",
"budget": "13,000,000",
"revenue": "102,600,000",
"genres": ["Crime","Drama"],
"releaseDate": "1974-12-20",
"actors": ["Al Pacino","Robert De Niro","Diane Keaton","Robert Duvall","John Cazale"],
"director": "Francis Ford Coppola",
"author": "Mario Puzo"
},

{
"id": 28,
"title": "Pulp Fiction",
"trailerURL": "https://youtu.be/s7EdQ4FqbhY",
"posterURL": "https://image.tmdb.org/t/p/original/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
"rating": 8.9,
"description": "Multiple interconnected stories unfold in the criminal underworld of Los Angeles.",
"budget": "8,000,000",
"revenue": "213,928,762",
"genres": ["Crime","Drama"],
"releaseDate": "1994-10-14",
"actors": ["John Travolta","Samuel L. Jackson","Uma Thurman","Bruce Willis","Tim Roth"],
"director": "Quentin Tarantino",
"author": "Quentin Tarantino"
},

{
"id": 29,
"title": "The Prestige",
"trailerURL": "https://youtu.be/RLtaA9fFNXU",
"posterURL": "https://image.tmdb.org/t/p/original/5MXyQfz8xUP3dIFPTubhTsbFY6N.jpg",
"rating": 8.5,
"description": "Two rival magicians engage in an intense battle to create the ultimate illusion.",
"budget": "40,000,000",
"revenue": "109,676,311",
"genres": ["Drama","Mystery"],
"releaseDate": "2006-10-20",
"actors": ["Christian Bale","Hugh Jackman","Scarlett Johansson","Michael Caine","David Bowie"],
"director": "Christopher Nolan",
"author": "Christopher Priest"
},

{
"id": 30,
"title": "Whiplash",
"trailerURL": "https://youtu.be/7d_jQycdQGo",
"posterURL": "https://image.tmdb.org/t/p/original/oPxnRhyAIzJKGUEdSiwTJQBa3NM.jpg",
"rating": 8.5,
"description": "A young drummer pushes himself to extreme limits under a ruthless music instructor.",
"budget": "3,300,000",
"revenue": "49,000,000",
"genres": ["Drama","Music"],
"releaseDate": "2014-10-10",
"actors": ["Miles Teller","J.K. Simmons","Melissa Benoist","Paul Reiser","Austin Stowell"],
"director": "Damien Chazelle",
"author": "Damien Chazelle"
},

{
"id": 31,
"title": "Mad Max: Fury Road",
"trailerURL": "https://youtu.be/hEJnMQG9ev8",
"posterURL": "https://image.tmdb.org/t/p/original/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
"rating": 8.1,
"description": "In a post-apocalyptic wasteland, Max teams with Furiosa to escape a tyrannical warlord.",
"budget": "150,000,000",
"revenue": "375,209,631",
"genres": ["Action","Adventure"],
"releaseDate": "2015-05-15",
"actors": ["Tom Hardy","Charlize Theron","Nicholas Hoult","Hugh Keays-Byrne","Rosie Huntington-Whiteley"],
"director": "George Miller",
"author": "George Miller"
},

{
"id": 32,
"title": "Parasite",
"trailerURL": "https://youtu.be/5xH0HfJHsaY",
"posterURL": "https://image.tmdb.org/t/p/original/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
"rating": 8.6,
"description": "A poor family schemes to infiltrate the lives of a wealthy household with unexpected consequences.",
"budget": "11,400,000",
"revenue": "258,800,000",
"genres": ["Drama","Thriller"],
"releaseDate": "2019-05-30",
"actors": ["Song Kang-ho","Lee Sun-kyun","Cho Yeo-jeong","Park So-dam","Choi Woo-shik"],
"director": "Bong Joon-ho",
"author": "Bong Joon-ho"
},

{
"id": 33,
"title": "1917",
"trailerURL": "https://youtu.be/YqNYrYUiMfg",
"posterURL": "https://image.tmdb.org/t/p/original/iZf0KyrE25z1sage4SYFLCCrMi9.jpg",
"rating": 8.3,
"description": "Two soldiers race against time during World War I to deliver a message that could save hundreds of lives.",
"budget": "95,000,000",
"revenue": "384,900,000",
"genres": ["War","Drama"],
"releaseDate": "2019-12-25",
"actors": ["George MacKay","Dean-Charles Chapman","Mark Strong","Colin Firth","Benedict Cumberbatch"],
"director": "Sam Mendes",
"author": "Sam Mendes"
},

{
"id": 34,
"title": "The Revenant",
"trailerURL": "https://youtu.be/LoebZZ8K5N0",
"posterURL": "https://image.tmdb.org/t/p/original/ji3ecJphATlVgWNY0B0RVXZizdf.jpg",
"rating": 8.0,
"description": "A frontiersman survives brutal wilderness conditions while seeking revenge against those who betrayed him.",
"budget": "135,000,000",
"revenue": "533,000,000",
"genres": ["Adventure","Drama"],
"releaseDate": "2015-12-25",
"actors": ["Leonardo DiCaprio","Tom Hardy","Domhnall Gleeson","Will Poulter","Forrest Goodluck"],
"director": "Alejandro G. Iñárritu",
"author": "Michael Punke"
},

{
"id": 35,
"title": "Gravity",
"trailerURL": "https://youtu.be/OiTiKOy59o4",
"posterURL": "https://image.tmdb.org/t/p/original/4iX3v2WqK9Uu8xdS6y5Z5jH3C0.jpg",
"rating": 7.7,
"description": "Two astronauts struggle to survive after their space shuttle is destroyed in orbit.",
"budget": "100,000,000",
"revenue": "723,192,705",
"genres": ["Sci-Fi","Drama"],
"releaseDate": "2013-10-04",
"actors": ["Sandra Bullock","George Clooney"],
"director": "Alfonso Cuarón",
"author": "Alfonso Cuarón"
},

{
"id": 36,
"title": "The Martian",
"trailerURL": "https://youtu.be/Ue4PCI0NamI",
"posterURL": "https://image.tmdb.org/t/p/original/5aGhaIHYuQbqlHWvWYqMCnj40y2.jpg",
"rating": 8.0,
"description": "An astronaut stranded on Mars must use science and ingenuity to survive until rescue arrives.",
"budget": "108,000,000",
"revenue": "630,620,818",
"genres": ["Sci-Fi","Adventure"],
"releaseDate": "2015-10-02",
"actors": ["Matt Damon","Jessica Chastain","Kate Mara","Jeff Daniels","Michael Peña"],
"director": "Ridley Scott",
"author": "Andy Weir"
},

{
"id": 37,
"title": "La La Land",
"trailerURL": "https://youtu.be/0pdqf4P9MB8",
"posterURL": "https://image.tmdb.org/t/p/original/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
"rating": 8.0,
"description": "A jazz musician and an aspiring actress fall in love while chasing dreams in Los Angeles.",
"budget": "30,000,000",
"revenue": "448,900,000",
"genres": ["Romance","Drama","Music"],
"releaseDate": "2016-12-09",
"actors": ["Ryan Gosling","Emma Stone","John Legend","Rosemarie DeWitt","Finn Wittrock"],
"director": "Damien Chazelle",
"author": "Damien Chazelle"
},

{
"id": 38,
"title": "Dune",
"trailerURL": "https://youtu.be/n9xhJrPXop4",
"posterURL": "https://image.tmdb.org/t/p/original/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
"rating": 8.0,
"description": "A noble family becomes embroiled in a galactic struggle over a precious resource on a desert planet.",
"budget": "165,000,000",
"revenue": "434,800,000",
"genres": ["Sci-Fi","Adventure"],
"releaseDate": "2021-10-22",
"actors": ["Timothée Chalamet","Zendaya","Oscar Isaac","Rebecca Ferguson","Jason Momoa"],
"director": "Denis Villeneuve",
"author": "Frank Herbert"
},

{
"id": 39,
"title": "Blade Runner 2049",
"trailerURL": "https://youtu.be/gCcx85zbxz4",
"posterURL": "https://image.tmdb.org/t/p/original/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
"rating": 8.0,
"description": "A new blade runner uncovers secrets that could change the future of humanity and replicants.",
"budget": "150,000,000",
"revenue": "260,500,000",
"genres": ["Sci-Fi","Drama"],
"releaseDate": "2017-10-06",
"actors": ["Ryan Gosling","Harrison Ford","Ana de Armas","Jared Leto","Robin Wright"],
"director": "Denis Villeneuve",
"author": "Philip K. Dick"
},

{
"id": 40,
"title": "The Grand Budapest Hotel",
"trailerURL": "https://youtu.be/1Fg5iWmQjwk",
"posterURL": "https://image.tmdb.org/t/p/original/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
"rating": 8.1,
"description": "The adventures of a legendary concierge and his protégé at a famous European hotel.",
"budget": "25,000,000",
"revenue": "172,900,000",
"genres": ["Comedy","Drama"],
"releaseDate": "2014-03-28",
"actors": ["Ralph Fiennes","Tony Revolori","Adrien Brody","Willem Dafoe","Saoirse Ronan"],
"director": "Wes Anderson",
"author": "Wes Anderson"
},

{
"id": 41,
"title": "Toy Story",
"trailerURL": "https://youtu.be/v-PjgYDrg70",
"posterURL": "https://image.tmdb.org/t/p/original/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
"rating": 8.3,
"description": "A group of toys comes to life when humans aren't around, led by cowboy Woody and space ranger Buzz.",
"budget": "30,000,000",
"revenue": "394,436,586",
"genres": ["Animation","Adventure"],
"releaseDate": "1995-11-22",
"actors": ["Tom Hanks","Tim Allen","Don Rickles","Jim Varney","Wallace Shawn"],
"director": "John Lasseter",
"author": "Joss Whedon"
},

{
"id": 42,
"title": "Finding Nemo",
"trailerURL": "https://youtu.be/wZdpNglLbt8",
"posterURL": "https://image.tmdb.org/t/p/original/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg",
"rating": 8.2,
"description": "A clownfish travels across the ocean to rescue his captured son.",
"budget": "94,000,000",
"revenue": "940,335,536",
"genres": ["Animation","Adventure"],
"releaseDate": "2003-05-30",
"actors": ["Albert Brooks","Ellen DeGeneres","Alexander Gould","Willem Dafoe"],
"director": "Andrew Stanton",
"author": "Andrew Stanton"
},

{
"id": 43,
"title": "Shrek",
"trailerURL": "https://youtu.be/CwXOrWvPBPk",
"posterURL": "https://image.tmdb.org/t/p/original/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg",
"rating": 7.9,
"description": "An ogre goes on a quest to rescue a princess and reclaim his swamp.",
"budget": "60,000,000",
"revenue": "487,900,000",
"genres": ["Animation","Comedy"],
"releaseDate": "2001-05-18",
"actors": ["Mike Myers","Eddie Murphy","Cameron Diaz","John Lithgow"],
"director": "Andrew Adamson",
"author": "William Steig"
},

{
"id": 44,
"title": "Frozen",
"trailerURL": "https://youtu.be/TbQm5doF_Uc",
"posterURL": "https://image.tmdb.org/t/p/original/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg",
"rating": 7.4,
"description": "Two royal sisters must overcome fear and misunderstanding to save their kingdom.",
"budget": "150,000,000",
"revenue": "1,290,000,000",
"genres": ["Animation","Adventure"],
"releaseDate": "2013-11-27",
"actors": ["Kristen Bell","Idina Menzel","Josh Gad","Jonathan Groff"],
"director": "Chris Buck",
"author": "Jennifer Lee"
},

{
"id": 45,
"title": "Moana",
"trailerURL": "https://youtu.be/LKFuXETZUsI",
"posterURL": "https://image.tmdb.org/t/p/original/4JeeqYQ4yHId4sIOLoPp6tdn2.jpg",
"rating": 7.6,
"description": "A young Polynesian girl sets sail to restore the heart of a goddess and save her island.",
"budget": "150,000,000",
"revenue": "690,800,000",
"genres": ["Animation","Adventure"],
"releaseDate": "2016-11-23",
"actors": ["Auli'i Cravalho","Dwayne Johnson","Rachel House"],
"director": "Ron Clements",
"author": "Jared Bush"
},

{
"id": 46,
"title": "Inside Out",
"trailerURL": "https://youtu.be/seMwpP0yeu4",
"posterURL": "https://image.tmdb.org/t/p/original/lRHE0vzf3oYJrhbsHXjIkF4Tl5A.jpg",
"rating": 8.1,
"description": "The emotions inside a young girl's mind guide her through life changes.",
"budget": "175,000,000",
"revenue": "858,800,000",
"genres": ["Animation","Comedy"],
"releaseDate": "2015-06-19",
"actors": ["Amy Poehler","Bill Hader","Mindy Kaling","Phyllis Smith"],
"director": "Pete Docter",
"author": "Pete Docter"
},

{
"id": 47,
"title": "Coco",
"trailerURL": "https://youtu.be/Rvr68u6k5sI",
"posterURL": "https://image.tmdb.org/t/p/original/eKi8dIrr8voobbaGzDpe8w0PVbC.jpg",
"rating": 8.4,
"description": "A young boy journeys into the Land of the Dead to uncover his family's musical past.",
"budget": "175,000,000",
"revenue": "814,300,000",
"genres": ["Animation","Adventure"],
"releaseDate": "2017-11-22",
"actors": ["Anthony Gonzalez","Gael García Bernal","Benjamin Bratt"],
"director": "Lee Unkrich",
"author": "Adrian Molina"
},

{
"id": 48,
"title": "Up",
"trailerURL": "https://youtu.be/ORFWdXl_zJ4",
"posterURL": "https://image.tmdb.org/t/p/original/mFvoEwSfLqbcWwFsDjQebn9bzFe.jpg",
"rating": 8.2,
"description": "An elderly man ties thousands of balloons to his house and flies to South America with a young stowaway.",
"budget": "175,000,000",
"revenue": "735,100,000",
"genres": ["Animation","Adventure"],
"releaseDate": "2009-05-29",
"actors": ["Ed Asner","Jordan Nagai","Christopher Plummer"],
"director": "Pete Docter",
"author": "Pete Docter"
},

{
"id": 49,
"title": "Ratatouille",
"trailerURL": "https://youtu.be/NgsQ8mVkN8w",
"posterURL": "https://image.tmdb.org/t/p/original/t3vaWRPSf6WjDSamIkKDs1iQWna.jpg",
"rating": 8.1,
"description": "A rat with a passion for cooking forms an unlikely partnership with a young kitchen worker.",
"budget": "150,000,000",
"revenue": "623,726,000",
"genres": ["Animation","Comedy"],
"releaseDate": "2007-06-29",
"actors": ["Patton Oswalt","Ian Holm","Lou Romano"],
"director": "Brad Bird",
"author": "Brad Bird"
},

{
"id": 50,
"title": "Wall-E",
"trailerURL": "https://youtu.be/CZ1CATNbXg0",
"posterURL": "https://image.tmdb.org/t/p/original/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg",
"rating": 8.4,
"description": "A lonely robot tasked with cleaning Earth discovers love and inadvertently saves humanity.",
"budget": "180,000,000",
"revenue": "533,281,433",
"genres": ["Animation","Sci-Fi"],
"releaseDate": "2008-06-27",
"actors": ["Ben Burtt","Elissa Knight","Jeff Garlin"],
"director": "Andrew Stanton",
"author": "Andrew Stanton"
},
{
"id": 51,
"title": "Edge of Tomorrow",
"trailerURL": "https://youtu.be/vw61gCe2oqI",
"posterURL": "https://image.tmdb.org/t/p/original/uUHvlkLavotfGsNtosDy8ShsIYF.jpg",
"rating": 7.9,
"description": "A soldier caught in a time loop relives the same battle against alien invaders and gradually becomes humanity's best hope for survival.",
"budget": "178,000,000",
"revenue": "370,541,256",
"genres": ["Action","Sci-Fi"],
"releaseDate": "2014-06-06",
"actors": ["Tom Cruise","Emily Blunt","Bill Paxton","Brendan Gleeson","Jonas Armstrong"],
"director": "Doug Liman",
"author": "Hiroshi Sakurazaka"
},

{
"id": 52,
"title": "Ready Player One",
"trailerURL": "https://youtu.be/cSp1dM2Vj48",
"posterURL": "https://image.tmdb.org/t/p/original/pU1ULUq8D3iRxl1fdX2lZIzdHuI.jpg",
"rating": 7.5,
"description": "In a dystopian future, people escape into a massive virtual reality world where a hidden treasure hunt could change their lives forever.",
"budget": "175,000,000",
"revenue": "607,274,134",
"genres": ["Adventure","Sci-Fi"],
"releaseDate": "2018-03-29",
"actors": ["Tye Sheridan","Olivia Cooke","Ben Mendelsohn","Mark Rylance","Simon Pegg"],
"director": "Steven Spielberg",
"author": "Ernest Cline"
},

{
"id": 53,
"title": "The Imitation Game",
"trailerURL": "https://youtu.be/S5CjKEFb-sM",
"posterURL": "https://image.tmdb.org/t/p/original/zSqJ1qFq8NXFfi7JeIYMlzyR0dx.jpg",
"rating": 8.0,
"description": "The story of mathematician Alan Turing and his team as they race to break Nazi Germany's Enigma code during World War II.",
"budget": "14,000,000",
"revenue": "233,555,708",
"genres": ["Drama","Biography"],
"releaseDate": "2014-11-28",
"actors": ["Benedict Cumberbatch","Keira Knightley","Matthew Goode","Mark Strong","Allen Leech"],
"director": "Morten Tyldum",
"author": "Graham Moore"
},

{
"id": 54,
"title": "A Quiet Place",
"trailerURL": "https://youtu.be/WR7cc5t7tv8",
"posterURL": "https://image.tmdb.org/t/p/original/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
"rating": 7.5,
"description": "A family must live in complete silence to avoid mysterious creatures that hunt by sound.",
"budget": "17,000,000",
"revenue": "341,013,807",
"genres": ["Horror","Thriller"],
"releaseDate": "2018-04-06",
"actors": ["Emily Blunt","John Krasinski","Millicent Simmonds","Noah Jupe"],
"director": "John Krasinski",
"author": "Bryan Woods"
},

{
"id": 55,
"title": "The Conjuring",
"trailerURL": "https://youtu.be/k10ETZ41q5o",
"posterURL": "https://image.tmdb.org/t/p/original/wVYREutTvI2tmxr6ujrHT704wGF.jpg",
"rating": 7.5,
"description": "Paranormal investigators Ed and Lorraine Warren help a family terrorized by a dark presence in their farmhouse.",
"budget": "20,000,000",
"revenue": "319,500,000",
"genres": ["Horror","Mystery"],
"releaseDate": "2013-07-19",
"actors": ["Vera Farmiga","Patrick Wilson","Lili Taylor","Ron Livingston"],
"director": "James Wan",
"author": "Chad Hayes"
},

{
"id": 56,
"title": "Get Out",
"trailerURL": "https://youtu.be/DzfpyUB60YY",
"posterURL": "https://image.tmdb.org/t/p/original/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
"rating": 7.8,
"description": "A young man uncovers disturbing secrets when visiting his girlfriend's mysterious family estate.",
"budget": "4,500,000",
"revenue": "255,407,969",
"genres": ["Horror","Thriller"],
"releaseDate": "2017-02-24",
"actors": ["Daniel Kaluuya","Allison Williams","Bradley Whitford","Catherine Keener"],
"director": "Jordan Peele",
"author": "Jordan Peele"
},

{
"id": 57,
"title": "Knives Out",
"trailerURL": "https://youtu.be/qGqiHJTsRkQ",
"posterURL": "https://image.tmdb.org/t/p/original/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
"rating": 7.9,
"description": "A detective investigates the mysterious death of a wealthy novelist during a chaotic family gathering.",
"budget": "40,000,000",
"revenue": "311,400,000",
"genres": ["Mystery","Comedy"],
"releaseDate": "2019-11-27",
"actors": ["Daniel Craig","Chris Evans","Ana de Armas","Jamie Lee Curtis","Michael Shannon"],
"director": "Rian Johnson",
"author": "Rian Johnson"
},

{
"id": 58,
"title": "Logan",
"trailerURL": "https://youtu.be/Div0iP65aZo",
"posterURL": "https://image.tmdb.org/t/p/original/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg",
"rating": 8.1,
"description": "An aging Wolverine must protect a young mutant girl while confronting his violent past.",
"budget": "97,000,000",
"revenue": "619,179,950",
"genres": ["Action","Drama"],
"releaseDate": "2017-03-03",
"actors": ["Hugh Jackman","Patrick Stewart","Dafne Keen","Boyd Holbrook"],
"director": "James Mangold",
"author": "James Mangold"
},

{
"id": 59,
"title": "The Batman",
"trailerURL": "https://youtu.be/mqqft2x_Aa4",
"posterURL": "https://image.tmdb.org/t/p/original/74xTEgt7R36Fpooo50r9T25onhq.jpg",
"rating": 7.8,
"description": "Batman investigates a series of brutal murders committed by the Riddler in Gotham City.",
"budget": "200,000,000",
"revenue": "770,836,163",
"genres": ["Action","Crime"],
"releaseDate": "2022-03-04",
"actors": ["Robert Pattinson","Zoë Kravitz","Paul Dano","Colin Farrell"],
"director": "Matt Reeves",
"author": "Matt Reeves"
},

{
"id": 60,
"title": "Tenet",
"trailerURL": "https://youtu.be/L3pk_TBkihU",
"posterURL": "https://image.tmdb.org/t/p/original/k68nPLbIST6NP96JmTxmZijEvCA.jpg",
"rating": 7.4,
"description": "A secret agent manipulates time itself while trying to prevent a global catastrophe.",
"budget": "205,000,000",
"revenue": "365,304,105",
"genres": ["Action","Sci-Fi"],
"releaseDate": "2020-08-26",
"actors": ["John David Washington","Robert Pattinson","Elizabeth Debicki","Kenneth Branagh"],
"director": "Christopher Nolan",
"author": "Christopher Nolan"
},

{
"id": 61,
"title": "The Truman Show",
"trailerURL": "https://youtu.be/dlnmQbPGuls",
"posterURL": "https://image.tmdb.org/t/p/original/bdCBp1uXw4rP9zE0pF9K0Qy8u8F.jpg",
"rating": 8.1,
"description": "A man slowly realizes that his entire life is actually a reality TV show broadcast to the world.",
"budget": "60,000,000",
"revenue": "264,118,201",
"genres": ["Drama","Comedy"],
"releaseDate": "1998-06-05",
"actors": ["Jim Carrey","Laura Linney","Ed Harris","Noah Emmerich"],
"director": "Peter Weir",
"author": "Andrew Niccol"
},

{
"id": 62,
"title": "The Bourne Identity",
"trailerURL": "https://youtu.be/cD-uQreIwEk",
"posterURL": "https://image.tmdb.org/t/p/original/aPkiXh0wqOa0n4p4m7S7n2l0V4T.jpg",
"rating": 7.9,
"description": "A man with severe memory loss discovers he possesses deadly combat skills and must uncover his true identity.",
"budget": "60,000,000",
"revenue": "214,034,224",
"genres": ["Action","Thriller"],
"releaseDate": "2002-06-14",
"actors": ["Matt Damon","Franka Potente","Chris Cooper","Clive Owen"],
"director": "Doug Liman",
"author": "Robert Ludlum"
},

{
"id": 63,
"title": "Mission Impossible Fallout",
"trailerURL": "https://youtu.be/wb49-oV0F78",
"posterURL": "https://image.tmdb.org/t/p/original/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg",
"rating": 7.7,
"description": "Ethan Hunt and his team race to stop a nuclear disaster after a mission goes wrong.",
"budget": "178,000,000",
"revenue": "791,115,104",
"genres": ["Action","Adventure"],
"releaseDate": "2018-07-27",
"actors": ["Tom Cruise","Henry Cavill","Rebecca Ferguson","Simon Pegg"],
"director": "Christopher McQuarrie",
"author": "Christopher McQuarrie"
},

{
"id": 64,
"title": "Ocean's Eleven",
"trailerURL": "https://youtu.be/imm6OR605UI",
"posterURL": "https://image.tmdb.org/t/p/original/hQQCdZrsHtZyR6NbKH2YyCqd2fR.jpg",
"rating": 7.7,
"description": "A group of professional criminals plan an elaborate heist to rob three Las Vegas casinos.",
"budget": "85,000,000",
"revenue": "450,717,150",
"genres": ["Crime","Comedy"],
"releaseDate": "2001-12-07",
"actors": ["George Clooney","Brad Pitt","Matt Damon","Julia Roberts"],
"director": "Steven Soderbergh",
"author": "Ted Griffin"
},

{
"id": 65,
"title": "Catch Me If You Can",
"trailerURL": "https://youtu.be/71rDQ7z4eFg",
"posterURL": "https://image.tmdb.org/t/p/original/ctjEj2xM32OvBXCq8zAdK3ZrsAj.jpg",
"rating": 8.1,
"description": "A brilliant con artist successfully impersonates professionals while being chased by an FBI agent.",
"budget": "52,000,000",
"revenue": "352,114,312",
"genres": ["Drama","Crime"],
"releaseDate": "2002-12-25",
"actors": ["Leonardo DiCaprio","Tom Hanks","Christopher Walken"],
"director": "Steven Spielberg",
"author": "Jeff Nathanson"
},

{
"id": 66,
"title": "Django Unchained",
"trailerURL": "https://youtu.be/eUdM9vrCbow",
"posterURL": "https://image.tmdb.org/t/p/original/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
"rating": 8.4,
"description": "A freed slave teams up with a bounty hunter to rescue his wife from a brutal plantation owner.",
"budget": "100,000,000",
"revenue": "425,368,238",
"genres": ["Western","Drama"],
"releaseDate": "2012-12-25",
"actors": ["Jamie Foxx","Christoph Waltz","Leonardo DiCaprio","Samuel L. Jackson"],
"director": "Quentin Tarantino",
"author": "Quentin Tarantino"
},

{
"id": 67,
"title": "Inglourious Basterds",
"trailerURL": "https://youtu.be/KnrRy6kSFF0",
"posterURL": "https://image.tmdb.org/t/p/original/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg",
"rating": 8.3,
"description": "A group of Jewish soldiers plot revenge against Nazi leaders during World War II.",
"budget": "70,000,000",
"revenue": "321,457,747",
"genres": ["War","Drama"],
"releaseDate": "2009-08-21",
"actors": ["Brad Pitt","Christoph Waltz","Michael Fassbender","Diane Kruger"],
"director": "Quentin Tarantino",
"author": "Quentin Tarantino"
},

{
"id": 68,
"title": "The Green Mile",
"trailerURL": "https://youtu.be/Ki4haFrqSrw",
"posterURL": "https://image.tmdb.org/t/p/original/velWPhVMQeQKcxggNEU8YmIo52R.jpg",
"rating": 8.6,
"description": "A prison guard witnesses supernatural events involving a death row inmate with mysterious powers.",
"budget": "60,000,000",
"revenue": "286,801,374",
"genres": ["Drama","Fantasy"],
"releaseDate": "1999-12-10",
"actors": ["Tom Hanks","Michael Clarke Duncan","David Morse"],
"director": "Frank Darabont",
"author": "Stephen King"
},

{
"id": 69,
"title": "The Departed",
"trailerURL": "https://youtu.be/iojhqm0JTW4",
"posterURL": "https://image.tmdb.org/t/p/original/kWWi2p3fA9c2vH4nY3F0kF5g7lj.jpg",
"rating": 8.5,
"description": "An undercover cop and a mole inside the police department try to identify each other while infiltrating an Irish crime gang.",
"budget": "90,000,000",
"revenue": "291,480,452",
"genres": ["Crime","Drama"],
"releaseDate": "2006-10-06",
"actors": ["Leonardo DiCaprio","Matt Damon","Jack Nicholson","Mark Wahlberg"],
"director": "Martin Scorsese",
"author": "William Monahan"
},

{
"id": 70,
"title": "Shutter Island",
"trailerURL": "https://youtu.be/5iaYLCiq5RM",
"posterURL": "https://image.tmdb.org/t/p/original/52HGsT6bHkzKntD3RkHyU9pXnFb.jpg",
"rating": 8.2,
"description": "A U.S. Marshal investigates a mysterious disappearance at a mental institution located on a remote island.",
"budget": "80,000,000",
"revenue": "294,804,195",
"genres": ["Thriller","Mystery"],
"releaseDate": "2010-02-19",
"actors": ["Leonardo DiCaprio","Mark Ruffalo","Ben Kingsley","Michelle Williams"],
"director": "Martin Scorsese",
"author": "Dennis Lehane"
},
{
"id": 71,
"title": "Guardians of the Galaxy",
"trailerURL": "https://youtu.be/d96cjJhvlMA",
"posterURL": "https://image.tmdb.org/t/p/original/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
"rating": 8.0,
"description": "A group of intergalactic criminals must work together to stop a fanatical warrior from destroying the galaxy.",
"budget": "170,000,000",
"revenue": "773,350,147",
"genres": ["Action","Adventure","Sci-Fi"],
"releaseDate": "2014-08-01",
"actors": ["Chris Pratt","Zoe Saldana","Dave Bautista","Bradley Cooper","Vin Diesel"],
"director": "James Gunn",
"author": "James Gunn"
},

{
"id": 72,
"title": "Thor Ragnarok",
"trailerURL": "https://youtu.be/ue80QwXMRHg",
"posterURL": "https://image.tmdb.org/t/p/original/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
"rating": 7.9,
"description": "Thor must escape imprisonment and stop the goddess Hela from destroying his home world of Asgard.",
"budget": "180,000,000",
"revenue": "854,000,000",
"genres": ["Action","Adventure","Fantasy"],
"releaseDate": "2017-11-03",
"actors": ["Chris Hemsworth","Tom Hiddleston","Cate Blanchett","Mark Ruffalo"],
"director": "Taika Waititi",
"author": "Eric Pearson"
},

{
"id": 73,
"title": "Captain America The Winter Soldier",
"trailerURL": "https://youtu.be/7SlILk2WMTI",
"posterURL": "https://image.tmdb.org/t/p/original/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg",
"rating": 7.8,
"description": "Captain America teams up with Black Widow to uncover a conspiracy within the government agency S.H.I.E.L.D.",
"budget": "170,000,000",
"revenue": "714,421,503",
"genres": ["Action","Adventure","Sci-Fi"],
"releaseDate": "2014-04-04",
"actors": ["Chris Evans","Scarlett Johansson","Sebastian Stan","Samuel L. Jackson"],
"director": "Anthony Russo",
"author": "Christopher Markus"
},

{
"id": 74,
"title": "Avengers Infinity War",
"trailerURL": "https://youtu.be/6ZfuNTqbHE8",
"posterURL": "https://image.tmdb.org/t/p/original/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
"rating": 8.4,
"description": "The Avengers and their allies must stop the powerful Thanos from collecting the Infinity Stones.",
"budget": "316,000,000",
"revenue": "2,048,359,754",
"genres": ["Action","Adventure","Sci-Fi"],
"releaseDate": "2018-04-27",
"actors": ["Robert Downey Jr.","Chris Evans","Scarlett Johansson","Chris Hemsworth","Josh Brolin"],
"director": "Anthony Russo",
"author": "Christopher Markus"
},

{
"id": 75,
"title": "Avengers Endgame",
"trailerURL": "https://youtu.be/TcMBFSGVi1c",
"posterURL": "https://image.tmdb.org/t/p/original/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
"rating": 8.4,
"description": "The surviving Avengers assemble once more to undo the damage caused by Thanos.",
"budget": "356,000,000",
"revenue": "2,797,501,328",
"genres": ["Action","Adventure","Sci-Fi"],
"releaseDate": "2019-04-26",
"actors": ["Robert Downey Jr.","Chris Evans","Mark Ruffalo","Chris Hemsworth","Scarlett Johansson"],
"director": "Anthony Russo",
"author": "Christopher Markus"
},

{
"id": 76,
"title": "Deadpool",
"trailerURL": "https://youtu.be/Xithigfg7dA",
"posterURL": "https://image.tmdb.org/t/p/original/inVq3FRqcYIRl2la8iZikYYxFNR.jpg",
"rating": 8.0,
"description": "A wisecracking mercenary with accelerated healing seeks revenge on the man who ruined his life.",
"budget": "58,000,000",
"revenue": "782,612,155",
"genres": ["Action","Comedy"],
"releaseDate": "2016-02-12",
"actors": ["Ryan Reynolds","Morena Baccarin","Ed Skrein","T.J. Miller"],
"director": "Tim Miller",
"author": "Rhett Reese"
},

{
"id": 77,
"title": "Deadpool 2",
"trailerURL": "https://youtu.be/D86RtevtfrA",
"posterURL": "https://image.tmdb.org/t/p/original/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg",
"rating": 7.7,
"description": "Deadpool forms a team of mutants to protect a young boy from a powerful cyborg soldier.",
"budget": "110,000,000",
"revenue": "785,046,920",
"genres": ["Action","Comedy"],
"releaseDate": "2018-05-18",
"actors": ["Ryan Reynolds","Josh Brolin","Zazie Beetz","Julian Dennison"],
"director": "David Leitch",
"author": "Rhett Reese"
},

{
"id": 78,
"title": "The Hunger Games",
"trailerURL": "https://youtu.be/PbA63a7H0bo",
"posterURL": "https://image.tmdb.org/t/p/original/iQK0pkT6p9V1YqXxRz5s3A1ZqA.jpg",
"rating": 7.2,
"description": "A young girl volunteers to compete in a deadly televised competition where only one contestant can survive.",
"budget": "78,000,000",
"revenue": "694,394,724",
"genres": ["Adventure","Sci-Fi"],
"releaseDate": "2012-03-23",
"actors": ["Jennifer Lawrence","Josh Hutcherson","Liam Hemsworth"],
"director": "Gary Ross",
"author": "Suzanne Collins"
},

{
"id": 79,
"title": "The Hunger Games Catching Fire",
"trailerURL": "https://youtu.be/EAzGXqJSDJ8",
"posterURL": "https://image.tmdb.org/t/p/original/7hUTqNQbX4qfZc6g3MZsG0zq2aL.jpg",
"rating": 7.5,
"description": "Katniss Everdeen returns to the arena as part of a special edition of the Hunger Games.",
"budget": "130,000,000",
"revenue": "865,011,746",
"genres": ["Adventure","Sci-Fi"],
"releaseDate": "2013-11-22",
"actors": ["Jennifer Lawrence","Josh Hutcherson","Liam Hemsworth"],
"director": "Francis Lawrence",
"author": "Suzanne Collins"
},

{
"id": 80,
"title": "The Hunger Games Mockingjay Part 1",
"trailerURL": "https://youtu.be/3PkkHsuMrho",
"posterURL": "https://image.tmdb.org/t/p/original/4FAA18ZIja70d1Tu5hr5cj2q1sB.jpg",
"rating": 6.6,
"description": "Katniss becomes the symbol of rebellion against the oppressive Capitol.",
"budget": "125,000,000",
"revenue": "755,000,000",
"genres": ["Adventure","Sci-Fi"],
"releaseDate": "2014-11-21",
"actors": ["Jennifer Lawrence","Josh Hutcherson","Liam Hemsworth"],
"director": "Francis Lawrence",
"author": "Suzanne Collins"
},

{
"id": 81,
"title": "The Hunger Games Mockingjay Part 2",
"trailerURL": "https://youtu.be/n-7K_OjsDCQ",
"posterURL": "https://image.tmdb.org/t/p/original/5w7H8z9h9L7C3sP7W2zdh0dX8G.jpg",
"rating": 6.7,
"description": "Katniss leads the final battle against President Snow and the Capitol.",
"budget": "160,000,000",
"revenue": "653,428,261",
"genres": ["Adventure","Sci-Fi"],
"releaseDate": "2015-11-20",
"actors": ["Jennifer Lawrence","Josh Hutcherson","Liam Hemsworth"],
"director": "Francis Lawrence",
"author": "Suzanne Collins"
},

{
"id": 82,
"title": "Transformers",
"trailerURL": "https://youtu.be/v8ItGrI-Ou0",
"posterURL": "https://image.tmdb.org/t/p/original/1XKjZ3G4fHYc0fE6S1P3tM.jpg",
"rating": 7.0,
"description": "Humans become caught in a war between alien robots who can transform into machines.",
"budget": "150,000,000",
"revenue": "709,709,780",
"genres": ["Action","Sci-Fi"],
"releaseDate": "2007-07-03",
"actors": ["Shia LaBeouf","Megan Fox","Josh Duhamel"],
"director": "Michael Bay",
"author": "Roberto Orci"
},

{
"id": 83,
"title": "Transformers Dark of the Moon",
"trailerURL": "https://youtu.be/NZlG28B-R8Y",
"posterURL": "https://image.tmdb.org/t/p/original/csS6h9q0K4rP5P2k3sF2f.jpg",
"rating": 6.2,
"description": "The Autobots learn about a Cybertronian spacecraft hidden on the moon that could end the war.",
"budget": "195,000,000",
"revenue": "1,123,794,079",
"genres": ["Action","Sci-Fi"],
"releaseDate": "2011-06-29",
"actors": ["Shia LaBeouf","Rosie Huntington-Whiteley","Josh Duhamel"],
"director": "Michael Bay",
"author": "Ehren Kruger"
},

{
"id": 84,
"title": "Pacific Rim",
"trailerURL": "https://youtu.be/5guMumPFBag",
"posterURL": "https://image.tmdb.org/t/p/original/mmznhaQDwlHWpUwKuNxtqiubbmM.jpg",
"rating": 7.0,
"description": "Giant robots controlled by humans fight monstrous creatures rising from the ocean depths.",
"budget": "190,000,000",
"revenue": "411,000,000",
"genres": ["Action","Sci-Fi"],
"releaseDate": "2013-07-12",
"actors": ["Charlie Hunnam","Idris Elba","Rinko Kikuchi"],
"director": "Guillermo del Toro",
"author": "Travis Beacham"
},

{
"id": 85,
"title": "Godzilla",
"trailerURL": "https://youtu.be/vIu85WQTPRc",
"posterURL": "https://image.tmdb.org/t/p/original/ApYedg5b7s7u9z3y.jpg",
"rating": 6.4,
"description": "Humanity faces the destructive power of the legendary monster Godzilla.",
"budget": "160,000,000",
"revenue": "529,000,000",
"genres": ["Action","Sci-Fi"],
"releaseDate": "2014-05-16",
"actors": ["Aaron Taylor-Johnson","Elizabeth Olsen","Bryan Cranston"],
"director": "Gareth Edwards",
"author": "Max Borenstein"
},

{
"id": 86,
"title": "King Kong",
"trailerURL": "https://youtu.be/AYaTCPbYGdk",
"posterURL": "https://image.tmdb.org/t/p/original/6iQ4CMtY.jpg",
"rating": 7.2,
"description": "A film crew discovers a massive ape on a mysterious island and attempts to bring it back to civilization.",
"budget": "207,000,000",
"revenue": "562,000,000",
"genres": ["Adventure","Fantasy"],
"releaseDate": "2005-12-14",
"actors": ["Naomi Watts","Jack Black","Adrien Brody"],
"director": "Peter Jackson",
"author": "Fran Walsh"
},

{
"id": 87,
"title": "Skyscraper",
"trailerURL": "https://youtu.be/t9QePUT-Yt8",
"posterURL": "https://image.tmdb.org/t/p/original/oMKFQmoVgB69fyXfSMu0lGlHJP2.jpg",
"rating": 6.0,
"description": "A security expert must rescue his family from a burning skyscraper taken over by criminals.",
"budget": "125,000,000",
"revenue": "304,000,000",
"genres": ["Action","Thriller"],
"releaseDate": "2018-07-13",
"actors": ["Dwayne Johnson","Neve Campbell","Chin Han"],
"director": "Rawson Marshall Thurber",
"author": "Rawson Marshall Thurber"
},

{
"id": 88,
"title": "San Andreas",
"trailerURL": "https://youtu.be/yftHosO0eUo",
"posterURL": "https://image.tmdb.org/t/p/original/cUfGqafAVQkatQ7N4y08RNV3bgu.jpg",
"rating": 6.5,
"description": "A massive earthquake devastates California, forcing a rescue pilot to save his family.",
"budget": "110,000,000",
"revenue": "474,000,000",
"genres": ["Action","Disaster"],
"releaseDate": "2015-05-29",
"actors": ["Dwayne Johnson","Carla Gugino","Alexandra Daddario"],
"director": "Brad Peyton",
"author": "Carlton Cuse"
},

{
"id": 89,
"title": "Rampage",
"trailerURL": "https://youtu.be/coOKvrsmQiI",
"posterURL": "https://image.tmdb.org/t/p/original/3gIOuAJ2XWblz2L8.jpg",
"rating": 6.1,
"description": "A primatologist teams with a giant mutated gorilla to stop other monstrous creatures.",
"budget": "120,000,000",
"revenue": "428,000,000",
"genres": ["Action","Adventure"],
"releaseDate": "2018-04-13",
"actors": ["Dwayne Johnson","Naomie Harris","Jeffrey Dean Morgan"],
"director": "Brad Peyton",
"author": "Ryan Engle"
},

{
"id": 90,
"title": "Jumanji Welcome to the Jungle",
"trailerURL": "https://youtu.be/2QKg5SZ_35I",
"posterURL": "https://image.tmdb.org/t/p/original/pSgXKPU5h6U89ipF7HBYajvYt7j.jpg",
"rating": 7.0,
"description": "Four teenagers are transported into a dangerous jungle video game world.",
"budget": "90,000,000",
"revenue": "962,542,945",
"genres": ["Adventure","Comedy"],
"releaseDate": "2017-12-20",
"actors": ["Dwayne Johnson","Kevin Hart","Jack Black","Karen Gillan"],
"director": "Jake Kasdan",
"author": "Chris McKenna"
},

{
"id": 91,
"title": "Jumanji The Next Level",
"trailerURL": "https://youtu.be/rBxcF-r9Ibs",
"posterURL": "https://image.tmdb.org/t/p/original/jyw8VKYEiM1UDzPB7NsisUgBeJ8.jpg",
"rating": 6.7,
"description": "The gang returns to Jumanji to rescue a friend and faces new dangerous environments.",
"budget": "125,000,000",
"revenue": "800,059,707",
"genres": ["Adventure","Comedy"],
"releaseDate": "2019-12-13",
"actors": ["Dwayne Johnson","Kevin Hart","Jack Black","Karen Gillan"],
"director": "Jake Kasdan",
"author": "Jake Kasdan"
},

{
"id": 92,
"title": "Night at the Museum",
"trailerURL": "https://youtu.be/X2IsugrA8lE",
"posterURL": "https://image.tmdb.org/t/p/original/6MpN7t2.jpg",
"rating": 6.5,
"description": "A night security guard discovers museum exhibits magically come to life after dark.",
"budget": "110,000,000",
"revenue": "574,000,000",
"genres": ["Adventure","Comedy"],
"releaseDate": "2006-12-22",
"actors": ["Ben Stiller","Robin Williams","Owen Wilson"],
"director": "Shawn Levy",
"author": "Robert Ben Garant"
},

{
"id": 93,
"title": "The Mummy",
"trailerURL": "https://youtu.be/IjHgzkQM2Sg",
"posterURL": "https://image.tmdb.org/t/p/original/yhIsVvcUm7QxzLfT6HW2wLf5ajY.jpg",
"rating": 7.0,
"description": "Adventurers accidentally awaken a cursed Egyptian mummy and must stop it.",
"budget": "80,000,000",
"revenue": "416,385,488",
"genres": ["Adventure","Fantasy"],
"releaseDate": "1999-05-07",
"actors": ["Brendan Fraser","Rachel Weisz","John Hannah"],
"director": "Stephen Sommers",
"author": "Stephen Sommers"
},

{
"id": 94,
"title": "National Treasure",
"trailerURL": "https://youtu.be/9d9L4pUqY7k",
"posterURL": "https://image.tmdb.org/t/p/original/mT7k.jpg",
"rating": 6.9,
"description": "A treasure hunter follows historical clues hidden in American landmarks.",
"budget": "100,000,000",
"revenue": "347,500,000",
"genres": ["Adventure","Mystery"],
"releaseDate": "2004-11-19",
"actors": ["Nicolas Cage","Diane Kruger","Justin Bartha"],
"director": "Jon Turteltaub",
"author": "Jim Kouf"
},

{
"id": 95,
"title": "Sherlock Holmes",
"trailerURL": "https://youtu.be/iKUQYg0vVJc",
"posterURL": "https://image.tmdb.org/t/p/original/momkKuWburNTqKBF6ez7rvhYVhE.jpg",
"rating": 7.6,
"description": "Detective Sherlock Holmes and Dr. Watson battle a mysterious villain threatening London.",
"budget": "90,000,000",
"revenue": "524,000,000",
"genres": ["Action","Mystery"],
"releaseDate": "2009-12-25",
"actors": ["Robert Downey Jr.","Jude Law","Rachel McAdams"],
"director": "Guy Ritchie",
"author": "Michael Robert Johnson"
},

{
"id": 96,
"title": "Sherlock Holmes A Game of Shadows",
"trailerURL": "https://youtu.be/cB6eJ9eU1e8",
"posterURL": "https://image.tmdb.org/t/p/original/wtqK3e.jpg",
"rating": 7.4,
"description": "Sherlock Holmes faces his greatest enemy Professor Moriarty.",
"budget": "125,000,000",
"revenue": "545,000,000",
"genres": ["Action","Mystery"],
"releaseDate": "2011-12-16",
"actors": ["Robert Downey Jr.","Jude Law","Noomi Rapace"],
"director": "Guy Ritchie",
"author": "Kieran Mulroney"
},

{
"id": 97,
"title": "The Meg",
"trailerURL": "https://youtu.be/udm5jUA-2bs",
"posterURL": "https://image.tmdb.org/t/p/original/xqECHNvzbDL5I3iiOVUkVPJMSbc.jpg",
"rating": 6.1,
"description": "A deep sea rescue diver faces a gigantic prehistoric shark.",
"budget": "130,000,000",
"revenue": "530,200,000",
"genres": ["Action","Sci-Fi"],
"releaseDate": "2018-08-10",
"actors": ["Jason Statham","Li Bingbing","Rainn Wilson"],
"director": "Jon Turteltaub",
"author": "Dean Georgaris"
},

{
"id": 98,
"title": "The Day After Tomorrow",
"trailerURL": "https://youtu.be/Ku_IseK3xTc",
"posterURL": "https://image.tmdb.org/t/p/original/pRmpa.jpg",
"rating": 6.5,
"description": "A global climate disaster forces humanity to fight for survival.",
"budget": "125,000,000",
"revenue": "552,639,571",
"genres": ["Action","Disaster"],
"releaseDate": "2004-05-28",
"actors": ["Dennis Quaid","Jake Gyllenhaal","Emmy Rossum"],
"director": "Roland Emmerich",
"author": "Roland Emmerich"
},

{
"id": 99,
"title": "2012",
"trailerURL": "https://youtu.be/sFXGrTng0gQ",
"posterURL": "https://image.tmdb.org/t/p/original/zaqam2RNscH5ooYFWInV6hjx6GV.jpg",
"rating": 5.8,
"description": "A series of catastrophic natural disasters threaten to destroy the world.",
"budget": "200,000,000",
"revenue": "791,217,826",
"genres": ["Action","Disaster"],
"releaseDate": "2009-11-13",
"actors": ["John Cusack","Amanda Peet","Chiwetel Ejiofor"],
"director": "Roland Emmerich",
"author": "Roland Emmerich"
},
{
"id": 100,
"title": "Armageddon",
"trailerURL": "https://youtu.be/kg_jH47u480",
"posterURL": "https://image.tmdb.org/t/p/original/eTM3qtGhDU8cvjpoa6KEt5GJ. jpg",
"rating": 6.7,
"description": "A group of oil drillers is sent into space to destroy an asteroid heading toward Earth.",
"budget": "140,000,000",
"revenue": "553,709,788",
"genres": ["Action","Sci-Fi"],
"releaseDate": "1998-07-01",
"actors": ["Bruce Willis","Ben Affleck","Liv Tyler"],
"director": "Michael Bay",
"author": "Jonathan Hensleigh"
}

]
module.exports = movies
