const movies = [
  {
    "id": 1,
    "title": "Inception",
    "trailerURL": "https://youtu.be/YoHD9XEInc0",
    "posterURL": "https://image.tmdb.org/t/p/original/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    "rating": 8.8,
    "description": "A skilled thief who steals secrets by entering people’s dreams is tasked with planting an idea in someone’s subconscious.",
    "budget": "160,000,000",
    "revenue": "829,895,144",
    "genres": ["Action","Sci-Fi","Thriller"],
    "releaseDate": "2010-07-15",
    "actors": ["Leonardo DiCaprio","Joseph Gordon-Levitt","Elliot Page","Tom Hardy","Ken Watanabe"],
    "director": "Christopher Nolan",
    "author": "Christopher Nolan"
  },
  {
    "id": 2,
    "title": "The Dark Knight",
    "trailerURL": "https://youtu.be/EXeTwQWrcwY",
    "posterURL": "https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    "rating": 9.0,
    "description": "Batman faces the Joker, who plunges Gotham into chaos while forcing Batman to confront his own moral code.",
    "budget": "185,000,000",
    "revenue": "1,004,558,444",
    "genres": ["Action","Crime","Drama"],
    "releaseDate": "2008-07-18",
    "actors": ["Christian Bale","Heath Ledger","Aaron Eckhart","Michael Caine","Maggie Gyllenhaal"],
    "director": "Christopher Nolan",
    "author": "Jonathan Nolan"
  },
  {
    "id": 3,
    "title": "The Shawshank Redemption",
    "trailerURL": "https://youtu.be/6hB3S9bIaco",
    "posterURL": "https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    "rating": 8.7,
    "description": "Two imprisoned men bond over years, finding hope and purpose despite harsh prison life.",
    "budget": "25,000,000",
    "revenue": "28,341,469",
    "genres": ["Drama","Crime"],
    "releaseDate": "1994-09-23",
    "actors": ["Tim Robbins","Morgan Freeman","Bob Gunton","William Sadler","Clancy Brown"],
    "director": "Frank Darabont",
    "author": "Stephen King"
  },
  {
    "id": 4,
    "title": "Fight Club",
    "trailerURL": "https://youtu.be/SUXWAEX2jlg",
    "posterURL": "https://image.tmdb.org/t/p/original/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg",
    "rating": 8.4,
    "description": "An insomniac white-collar worker forms an underground fight club with a soap salesman, changing both their lives.",
    "budget": "63,000,000",
    "revenue": "100,853,753",
    "genres": ["Drama"],
    "releaseDate": "1999-10-15",
    "actors": ["Brad Pitt","Edward Norton","Meat Loaf","Jared Leto","Helena Bonham Carter"],
    "director": "David Fincher",
    "author": "Chuck Palahniuk"
  },
  {
    "id": 5,
    "title": "Forrest Gump",
    "trailerURL": "https://youtu.be/bLvqoHBptjg",
    "posterURL": "https://image.tmdb.org/t/p/original/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
    "rating": 8.8,
    "description": "A man with a low IQ recounts the extraordinary events of his life while sitting at a bus stop.",
    "budget": "55,000,000",
    "revenue": "678,222,284",
    "genres": ["Drama","Romance"],
    "releaseDate": "1994-07-06",
    "actors": ["Tom Hanks","Robin Wright","Gary Sinise","Mykelti Williamson","Sally Field"],
    "director": "Robert Zemeckis",
    "author": "Winston Groom"
  },
  {
    "id": 6,
    "title": "The Lord of the Rings: The Return of the King",
    "trailerURL": "https://youtu.be/r5X-hFf6Bwo",
    "posterURL": "https://image.tmdb.org/t/p/original/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    "rating": 8.9,
    "description": "The final confrontation between the forces of good and evil fighting for control of Middle‑earth.",
    "budget": "94,000,000",
    "revenue": "1,146,030,912",
    "genres": ["Adventure","Fantasy","Action"],
    "releaseDate": "2003-12-17",
    "actors": ["Elijah Wood","Viggo Mortensen","Ian McKellen","Orlando Bloom","Sean Astin"],
    "director": "Peter Jackson",
    "author": "J.R.R. Tolkien"
  },
  {
    "id": 7,
    "title": "Interstellar",
    "trailerURL": "https://youtu.be/zSWdZVtXT7E",
    "posterURL": "https://image.tmdb.org/t/p/original/81kzL9sx-3L._AC_SL1500_.jpg",
    "rating": 8.6,
    "description": "A team of explorers travels through a wormhole in space to ensure humanity’s survival.",
    "budget": "165,000,000",
    "revenue": "677,471,339",
    "genres": ["Adventure","Drama","Sci‑Fi"],
    "releaseDate": "2014-11-07",
    "actors": ["Matthew McConaughey","Anne Hathaway","Jessica Chastain","Michael Caine","Casey Affleck"],
    "director": "Christopher Nolan",
    "author": "Jonathan Nolan"
  },
  {
    "id": 8,
    "title": "Gladiator",
    "trailerURL": "https://youtu.be/owK1qxDselE",
    "posterURL": "https://image.tmdb.org/t/p/original/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    "rating": 8.5,
    "description": "A betrayed Roman general rises as a gladiator to seek revenge against the corrupt emperor.",
    "budget": "103,000,000",
    "revenue": "460,583,960",
    "genres": ["Action","Drama","Adventure"],
    "releaseDate": "2000-05-05",
    "actors": ["Russell Crowe","Joaquin Phoenix","Connie Nielsen","Oliver Reed","Derek Jacobi"],
    "director": "Ridley Scott",
    "author": "David Franzoni"
  },
  {
    "id": 9,
    "title": "The Matrix",
    "trailerURL": "https://youtu.be/vKQi3bBA1y8",
    "posterURL": "https://image.tmdb.org/t/p/original/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    "rating": 8.7,
    "description": "A hacker discovers reality is a simulation and joins rebels to free humanity from machines.",
    "budget": "63,000,000",
    "revenue": "463,517,383",
    "genres": ["Action","Sci‑Fi"],
    "releaseDate": "1999-03-31",
    "actors": ["Keanu Reeves","Laurence Fishburne","Carrie‑Anne Moss","Hugo Weaving","Joe Pantoliano"],
    "director": "The Wachowskis",
    "author": "The Wachowskis"
  },
  {
    "id": 10,
    "title": "Avatar",
    "trailerURL": "https://youtu.be/5PSNL1qE6VY",
    "posterURL": "https://image.tmdb.org/t/p/original/6EiRUJpuoeQPghrs3YNktfnqOVh.jpg",
    "rating": 7.8,
    "description": "On the alien world of Pandora, humans clash with indigenous Na’vi over resources and survival.",
    "budget": "237,000,000",
    "revenue": "2,847,246,203",
    "genres": ["Action","Adventure","Fantasy"],
    "releaseDate": "2009-12-18",
    "actors": ["Sam Worthington","Zoe Saldana","Sigourney Weaver","Stephen Lang","Michelle Rodriguez"],
    "director": "James Cameron",
    "author": "James Cameron"
  },
  {
    "id": 11,
    "title": "Titanic",
    "trailerURL": "https://youtu.be/kVrqfYjkTdQ",
    "posterURL": "https://image.tmdb.org/t/p/original/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    "rating": 7.9,
    "description": "A young couple falls in love aboard the ill‑fated RMS Titanic while tragedy unfolds.",
    "budget": "200,000,000",
    "revenue": "2,201,647,264",
    "genres": ["Drama","Romance"],
    "releaseDate": "1997-12-19",
    "actors": ["Leonardo DiCaprio","Kate Winslet","Billy Zane","Kathy Bates","Frances Fisher"],
    "director": "James Cameron",
    "author": "James Cameron"
  },
  {
    "id": 12,
    "title": "Jurassic Park",
    "trailerURL": "https://youtu.be/QWBKEmWWL38",
    "posterURL": "https://image.tmdb.org/t/p/original/fcikG74LY9H9y7AR2mkhyYcQWtv.jpg",
    "rating": 8.1,
    "description": "Scientists resurrect dinosaurs for a theme park, leading to chaos and survival battles.",
    "budget": "63,000,000",
    "revenue": "1,033,919,889",
    "genres": ["Action","Adventure","Sci‑Fi"],
    "releaseDate": "1993-06-11",
    "actors": ["Sam Neill","Laura Dern","Jeff Goldblum","Richard Attenborough","Bob Peck"],
    "director": "Steven Spielberg",
    "author": "Michael Crichton"
  },
  {
    "id": 13,
    "title": "The Lion King",
    "trailerURL": "https://youtu.be/7TavVZMewpY",
    "posterURL": "https://image.tmdb.org/t/p/original/sKCr78MXSLbx5kSyvMqVvXa9Bt2.jpg",
    "rating": 8.5,
    "description": "A young lion prince flees after his father’s death, later returning to claim his place in the Circle of Life.",
    "budget": "45,000,000",
    "revenue": "968,483,777",
    "genres": ["Animation","Adventure","Drama"],
    "releaseDate": "1994-06-24",
    "actors": ["Matthew Broderick","Jeremy Irons","James Earl Jones","Whoopi Goldberg","Nathan Lane"],
    "director": "Roger Allers & Rob Minkoff",
    "author": "Irene Mecchi"
  },
  {
    "id": 14,
    "title": "Back to the Future",
    "trailerURL": "https://youtu.be/qvsgGtivCgs",
    "posterURL": "https://image.tmdb.org/t/p/original/pTpxQB9kq2wXdZxMtNNFh18OZCB.jpg",
    "rating": 8.5,
    "description": "A teen is accidentally sent back in time, jeopardizing his parents’ future and struggling to fix history.",
    "budget": "19,000,000",
    "revenue": "389,113,867",
    "genres": ["Adventure","Comedy","Sci‑Fi"],
    "releaseDate": "1985-07-03",
    "actors": ["Michael J. Fox","Christopher Lloyd","Lea Thompson","Crispin Glover","Thomas F. Wilson"],
    "director": "Robert Zemeckis",
    "author": "Robert Zemeckis"
  },
  {
    "id": 15,
    "title": "Terminator 2: Judgment Day",
    "trailerURL": "https://youtu.be/eajuMYNYtuY",
    "posterURL": "https://image.tmdb.org/t/p/original/9Sw0gFzRm3FQIqvFa0b6O3KJ2hS.jpg",
    "rating": 8.5,
    "description": "A cyborg must protect a boy from a more advanced terminator from the future.",
    "budget": "102,000,000",
    "revenue": "520,881,154",
    "genres": ["Action","Sci‑Fi"],
    "releaseDate": "1991-07-03",
    "actors": ["Arnold Schwarzenegger","Linda Hamilton","Edward Furlong","Robert Patrick","Earl Boen"],
    "director": "James Cameron",
    "author": "James Cameron"
  },
  {
    "id": 16,
    "title": "Star Wars: Episode IV – A New Hope",
    "trailerURL": "https://youtu.be/vZ734NWnAHA",
    "posterURL": "https://image.tmdb.org/t/p/original/rqAEzIFw5cgI6Ii6fM7uVeFQXcQ.jpg",
    "rating": 8.6,
    "description": "A farm boy joins forces with rebels to save the galaxy from a tyrannical empire.",
    "budget": "11,000,000",
    "revenue": "775,398,007",
    "genres": ["Adventure","Sci‑Fi","Action"],
    "releaseDate": "1977-05-25",
    "actors": ["Mark Hamill","Harrison Ford","Carrie Fisher","Alec Guinness","Peter Cushing"],
    "director": "George Lucas",
    "author": "George Lucas"
  },
  {
"id": 17,
"title": "The Avengers",
"trailerURL": "https://youtu.be/eOrNdBpGMv8",
"posterURL": "https://image.tmdb.org/t/p/original/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
"rating": 8.0,
"description": "Earth's mightiest heroes assemble to stop the god Loki and his alien army from conquering Earth.",
"budget": "220,000,000",
"revenue": "1,518,812,988",
"genres": ["Action","Adventure","Sci-Fi"],
"releaseDate": "2012-05-04",
"actors": ["Robert Downey Jr.","Chris Evans","Scarlett Johansson","Mark Ruffalo","Chris Hemsworth"],
"director": "Joss Whedon",
"author": "Zak Penn"
},

{
"id": 18,
"title": "Iron Man",
"trailerURL": "https://youtu.be/8hYlB38asDY",
"posterURL": "https://image.tmdb.org/t/p/original/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
"rating": 7.9,
"description": "A billionaire inventor builds a powerful armored suit after escaping captivity and becomes the hero Iron Man.",
"budget": "140,000,000",
"revenue": "585,796,247",
"genres": ["Action","Sci-Fi"],
"releaseDate": "2008-05-02",
"actors": ["Robert Downey Jr.","Gwyneth Paltrow","Jeff Bridges","Terrence Howard","Clark Gregg"],
"director": "Jon Favreau",
"author": "Mark Fergus"
},

{
"id": 19,
"title": "Black Panther",
"trailerURL": "https://youtu.be/xjDjIWPwcPU",
"posterURL": "https://image.tmdb.org/t/p/original/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
"rating": 7.3,
"description": "The king of Wakanda must defend his nation and the powerful vibranium technology from enemies.",
"budget": "200,000,000",
"revenue": "1,347,597,973",
"genres": ["Action","Adventure"],
"releaseDate": "2018-02-16",
"actors": ["Chadwick Boseman","Michael B. Jordan","Lupita Nyong'o","Danai Gurira","Martin Freeman"],
"director": "Ryan Coogler",
"author": "Ryan Coogler"
},

{
"id": 20,
"title": "Doctor Strange",
"trailerURL": "https://youtu.be/HSzx-zryEgM",
"posterURL": "https://image.tmdb.org/t/p/original/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg",
"rating": 7.5,
"description": "A brilliant but arrogant surgeon discovers the hidden world of mystic arts after a life-changing accident.",
"budget": "165,000,000",
"revenue": "677,718,395",
"genres": ["Action","Fantasy"],
"releaseDate": "2016-11-04",
"actors": ["Benedict Cumberbatch","Rachel McAdams","Tilda Swinton","Chiwetel Ejiofor","Mads Mikkelsen"],
"director": "Scott Derrickson",
"author": "Jon Spaihts"
},

{
"id": 21,
"title": "Spider-Man: Homecoming",
"trailerURL": "https://youtu.be/U0D3AOldjMU",
"posterURL": "https://image.tmdb.org/t/p/original/kY2c7wKgOfQjvbqe7yVzLTYkxJO.jpg",
"rating": 7.4,
"description": "Peter Parker balances high school life while proving himself worthy as Spider-Man.",
"budget": "175,000,000",
"revenue": "880,166,924",
"genres": ["Action","Adventure"],
"releaseDate": "2017-07-07",
"actors": ["Tom Holland","Michael Keaton","Robert Downey Jr.","Zendaya","Marisa Tomei"],
"director": "Jon Watts",
"author": "Jonathan Goldstein"
},

{
"id": 22,
"title": "Joker",
"trailerURL": "https://youtu.be/zAGVQLHvwOY",
"posterURL": "https://image.tmdb.org/t/p/original/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
"rating": 8.4,
"description": "A struggling comedian descends into madness and becomes Gotham City's most infamous criminal.",
"budget": "55,000,000",
"revenue": "1,074,458,282",
"genres": ["Crime","Drama","Thriller"],
"releaseDate": "2019-10-04",
"actors": ["Joaquin Phoenix","Robert De Niro","Zazie Beetz","Frances Conroy","Brett Cullen"],
"director": "Todd Phillips",
"author": "Todd Phillips"
},

{
"id": 23,
"title": "The Social Network",
"trailerURL": "https://youtu.be/lB95KLmpLR4",
"posterURL": "https://image.tmdb.org/t/p/original/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
"rating": 7.7,
"description": "The story of the founding of Facebook and the legal battles that followed.",
"budget": "40,000,000",
"revenue": "224,920,315",
"genres": ["Drama","Biography"],
"releaseDate": "2010-10-01",
"actors": ["Jesse Eisenberg","Andrew Garfield","Justin Timberlake","Armie Hammer","Max Minghella"],
"director": "David Fincher",
"author": "Aaron Sorkin"
},

{
"id": 24,
"title": "The Wolf of Wall Street",
"trailerURL": "https://youtu.be/iszwuX1AK6A",
"posterURL": "https://image.tmdb.org/t/p/original/pWHf4khOloNVfCxscsXFj3jj6gP.jpg",
"rating": 8.2,
"description": "A stockbroker rises to immense wealth through corruption and fraud before facing the consequences.",
"budget": "100,000,000",
"revenue": "406,878,233",
"genres": ["Biography","Drama"],
"releaseDate": "2013-12-25",
"actors": ["Leonardo DiCaprio","Jonah Hill","Margot Robbie","Matthew McConaughey","Kyle Chandler"],
"director": "Martin Scorsese",
"author": "Terence Winter"
},

{
"id": 25,
"title": "The Silence of the Lambs",
"trailerURL": "https://youtu.be/W6Mm8Sbe__o",
"posterURL": "https://image.tmdb.org/t/p/original/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg",
"rating": 8.6,
"description": "An FBI trainee seeks help from a brilliant cannibalistic psychiatrist to catch a serial killer.",
"budget": "19,000,000",
"revenue": "272,742,922",
"genres": ["Thriller","Crime"],
"releaseDate": "1991-02-14",
"actors": ["Jodie Foster","Anthony Hopkins","Scott Glenn","Ted Levine","Anthony Heald"],
"director": "Jonathan Demme",
"author": "Thomas Harris"
},

{
"id": 26,
"title": "The Godfather",
"trailerURL": "https://youtu.be/sY1S34973zA",
"posterURL": "https://image.tmdb.org/t/p/original/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
"rating": 9.2,
"description": "The aging patriarch of a powerful crime family transfers control of his empire to his reluctant son.",
"budget": "6,000,000",
"revenue": "246,120,974",
"genres": ["Crime","Drama"],
"releaseDate": "1972-03-24",
"actors": ["Marlon Brando","Al Pacino","James Caan","Robert Duvall","Diane Keaton"],
"director": "Francis Ford Coppola",
"author": "Mario Puzo"
},

{
"id": 27,
"title": "The Godfather Part II",
"trailerURL": "https://youtu.be/9O1Iy9od7-A",
"posterURL": "https://image.tmdb.org/t/p/original/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
"rating": 9.0,
"description": "The early life of Vito Corleone is contrasted with his son Michael's expansion of the family crime empire.",
"budget": "13,000,000",
"revenue": "102,600,000",
"genres": ["Crime","Drama"],
"releaseDate": "1974-12-20",
"actors": ["Al Pacino","Robert De Niro","Diane Keaton","Robert Duvall","John Cazale"],
"director": "Francis Ford Coppola",
"author": "Mario Puzo"
},

{
"id": 28,
"title": "Pulp Fiction",
"trailerURL": "https://youtu.be/s7EdQ4FqbhY",
"posterURL": "https://image.tmdb.org/t/p/original/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
"rating": 8.9,
"description": "Multiple interconnected stories unfold in the criminal underworld of Los Angeles.",
"budget": "8,000,000",
"revenue": "213,928,762",
"genres": ["Crime","Drama"],
"releaseDate": "1994-10-14",
"actors": ["John Travolta","Samuel L. Jackson","Uma Thurman","Bruce Willis","Tim Roth"],
"director": "Quentin Tarantino",
"author": "Quentin Tarantino"
},

{
"id": 29,
"title": "The Prestige",
"trailerURL": "https://youtu.be/RLtaA9fFNXU",
"posterURL": "https://image.tmdb.org/t/p/original/5MXyQfz8xUP3dIFPTubhTsbFY6N.jpg",
"rating": 8.5,
"description": "Two rival magicians engage in an intense battle to create the ultimate illusion.",
"budget": "40,000,000",
"revenue": "109,676,311",
"genres": ["Drama","Mystery"],
"releaseDate": "2006-10-20",
"actors": ["Christian Bale","Hugh Jackman","Scarlett Johansson","Michael Caine","David Bowie"],
"director": "Christopher Nolan",
"author": "Christopher Priest"
},

{
"id": 30,
"title": "Whiplash",
"trailerURL": "https://youtu.be/7d_jQycdQGo",
"posterURL": "https://image.tmdb.org/t/p/original/oPxnRhyAIzJKGUEdSiwTJQBa3NM.jpg",
"rating": 8.5,
"description": "A young drummer pushes himself to extreme limits under a ruthless music instructor.",
"budget": "3,300,000",
"revenue": "49,000,000",
"genres": ["Drama","Music"],
"releaseDate": "2014-10-10",
"actors": ["Miles Teller","J.K. Simmons","Melissa Benoist","Paul Reiser","Austin Stowell"],
"director": "Damien Chazelle",
"author": "Damien Chazelle"
},

{
"id": 31,
"title": "Mad Max: Fury Road",
"trailerURL": "https://youtu.be/hEJnMQG9ev8",
"posterURL": "https://image.tmdb.org/t/p/original/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
"rating": 8.1,
"description": "In a post-apocalyptic wasteland, Max teams with Furiosa to escape a tyrannical warlord.",
"budget": "150,000,000",
"revenue": "375,209,631",
"genres": ["Action","Adventure"],
"releaseDate": "2015-05-15",
"actors": ["Tom Hardy","Charlize Theron","Nicholas Hoult","Hugh Keays-Byrne","Rosie Huntington-Whiteley"],
"director": "George Miller",
"author": "George Miller"
},

{
"id": 32,
"title": "Parasite",
"trailerURL": "https://youtu.be/5xH0HfJHsaY",
"posterURL": "https://image.tmdb.org/t/p/original/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
"rating": 8.6,
"description": "A poor family schemes to infiltrate the lives of a wealthy household with unexpected consequences.",
"budget": "11,400,000",
"revenue": "258,800,000",
"genres": ["Drama","Thriller"],
"releaseDate": "2019-05-30",
"actors": ["Song Kang-ho","Lee Sun-kyun","Cho Yeo-jeong","Park So-dam","Choi Woo-shik"],
"director": "Bong Joon-ho",
"author": "Bong Joon-ho"
},

{
"id": 33,
"title": "1917",
"trailerURL": "https://youtu.be/YqNYrYUiMfg",
"posterURL": "https://image.tmdb.org/t/p/original/iZf0KyrE25z1sage4SYFLCCrMi9.jpg",
"rating": 8.3,
"description": "Two soldiers race against time during World War I to deliver a message that could save hundreds of lives.",
"budget": "95,000,000",
"revenue": "384,900,000",
"genres": ["War","Drama"],
"releaseDate": "2019-12-25",
"actors": ["George MacKay","Dean-Charles Chapman","Mark Strong","Colin Firth","Benedict Cumberbatch"],
"director": "Sam Mendes",
"author": "Sam Mendes"
},

{
"id": 34,
"title": "The Revenant",
"trailerURL": "https://youtu.be/LoebZZ8K5N0",
"posterURL": "https://image.tmdb.org/t/p/original/ji3ecJphATlVgWNY0B0RVXZizdf.jpg",
"rating": 8.0,
"description": "A frontiersman survives brutal wilderness conditions while seeking revenge against those who betrayed him.",
"budget": "135,000,000",
"revenue": "533,000,000",
"genres": ["Adventure","Drama"],
"releaseDate": "2015-12-25",
"actors": ["Leonardo DiCaprio","Tom Hardy","Domhnall Gleeson","Will Poulter","Forrest Goodluck"],
"director": "Alejandro G. Iñárritu",
"author": "Michael Punke"
},

{
"id": 35,
"title": "Gravity",
"trailerURL": "https://youtu.be/OiTiKOy59o4",
"posterURL": "https://image.tmdb.org/t/p/original/4iX3v2WqK9Uu8xdS6y5Z5jH3C0.jpg",
"rating": 7.7,
"description": "Two astronauts struggle to survive after their space shuttle is destroyed in orbit.",
"budget": "100,000,000",
"revenue": "723,192,705",
"genres": ["Sci-Fi","Drama"],
"releaseDate": "2013-10-04",
"actors": ["Sandra Bullock","George Clooney"],
"director": "Alfonso Cuarón",
"author": "Alfonso Cuarón"
},

{
"id": 36,
"title": "The Martian",
"trailerURL": "https://youtu.be/Ue4PCI0NamI",
"posterURL": "https://image.tmdb.org/t/p/original/5aGhaIHYuQbqlHWvWYqMCnj40y2.jpg",
"rating": 8.0,
"description": "An astronaut stranded on Mars must use science and ingenuity to survive until rescue arrives.",
"budget": "108,000,000",
"revenue": "630,620,818",
"genres": ["Sci-Fi","Adventure"],
"releaseDate": "2015-10-02",
"actors": ["Matt Damon","Jessica Chastain","Kate Mara","Jeff Daniels","Michael Peña"],
"director": "Ridley Scott",
"author": "Andy Weir"
},

{
"id": 37,
"title": "La La Land",
"trailerURL": "https://youtu.be/0pdqf4P9MB8",
"posterURL": "https://image.tmdb.org/t/p/original/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
"rating": 8.0,
"description": "A jazz musician and an aspiring actress fall in love while chasing dreams in Los Angeles.",
"budget": "30,000,000",
"revenue": "448,900,000",
"genres": ["Romance","Drama","Music"],
"releaseDate": "2016-12-09",
"actors": ["Ryan Gosling","Emma Stone","John Legend","Rosemarie DeWitt","Finn Wittrock"],
"director": "Damien Chazelle",
"author": "Damien Chazelle"
},

{
"id": 38,
"title": "Dune",
"trailerURL": "https://youtu.be/n9xhJrPXop4",
"posterURL": "https://image.tmdb.org/t/p/original/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
"rating": 8.0,
"description": "A noble family becomes embroiled in a galactic struggle over a precious resource on a desert planet.",
"budget": "165,000,000",
"revenue": "434,800,000",
"genres": ["Sci-Fi","Adventure"],
"releaseDate": "2021-10-22",
"actors": ["Timothée Chalamet","Zendaya","Oscar Isaac","Rebecca Ferguson","Jason Momoa"],
"director": "Denis Villeneuve",
"author": "Frank Herbert"
},

{
"id": 39,
"title": "Blade Runner 2049",
"trailerURL": "https://youtu.be/gCcx85zbxz4",
"posterURL": "https://image.tmdb.org/t/p/original/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
"rating": 8.0,
"description": "A new blade runner uncovers secrets that could change the future of humanity and replicants.",
"budget": "150,000,000",
"revenue": "260,500,000",
"genres": ["Sci-Fi","Drama"],
"releaseDate": "2017-10-06",
"actors": ["Ryan Gosling","Harrison Ford","Ana de Armas","Jared Leto","Robin Wright"],
"director": "Denis Villeneuve",
"author": "Philip K. Dick"
},

{
"id": 40,
"title": "The Grand Budapest Hotel",
"trailerURL": "https://youtu.be/1Fg5iWmQjwk",
"posterURL": "https://image.tmdb.org/t/p/original/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
"rating": 8.1,
"description": "The adventures of a legendary concierge and his protégé at a famous European hotel.",
"budget": "25,000,000",
"revenue": "172,900,000",
"genres": ["Comedy","Drama"],
"releaseDate": "2014-03-28",
"actors": ["Ralph Fiennes","Tony Revolori","Adrien Brody","Willem Dafoe","Saoirse Ronan"],
"director": "Wes Anderson",
"author": "Wes Anderson"
},

{
"id": 41,
"title": "Toy Story",
"trailerURL": "https://youtu.be/v-PjgYDrg70",
"posterURL": "https://image.tmdb.org/t/p/original/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
"rating": 8.3,
"description": "A group of toys comes to life when humans aren't around, led by cowboy Woody and space ranger Buzz.",
"budget": "30,000,000",
"revenue": "394,436,586",
"genres": ["Animation","Adventure"],
"releaseDate": "1995-11-22",
"actors": ["Tom Hanks","Tim Allen","Don Rickles","Jim Varney","Wallace Shawn"],
"director": "John Lasseter",
"author": "Joss Whedon"
},

{
"id": 42,
"title": "Finding Nemo",
"trailerURL": "https://youtu.be/wZdpNglLbt8",
"posterURL": "https://image.tmdb.org/t/p/original/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg",
"rating": 8.2,
"description": "A clownfish travels across the ocean to rescue his captured son.",
"budget": "94,000,000",
"revenue": "940,335,536",
"genres": ["Animation","Adventure"],
"releaseDate": "2003-05-30",
"actors": ["Albert Brooks","Ellen DeGeneres","Alexander Gould","Willem Dafoe"],
"director": "Andrew Stanton",
"author": "Andrew Stanton"
},

{
"id": 43,
"title": "Shrek",
"trailerURL": "https://youtu.be/CwXOrWvPBPk",
"posterURL": "https://image.tmdb.org/t/p/original/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg",
"rating": 7.9,
"description": "An ogre goes on a quest to rescue a princess and reclaim his swamp.",
"budget": "60,000,000",
"revenue": "487,900,000",
"genres": ["Animation","Comedy"],
"releaseDate": "2001-05-18",
"actors": ["Mike Myers","Eddie Murphy","Cameron Diaz","John Lithgow"],
"director": "Andrew Adamson",
"author": "William Steig"
},

{
"id": 44,
"title": "Frozen",
"trailerURL": "https://youtu.be/TbQm5doF_Uc",
"posterURL": "https://image.tmdb.org/t/p/original/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg",
"rating": 7.4,
"description": "Two royal sisters must overcome fear and misunderstanding to save their kingdom.",
"budget": "150,000,000",
"revenue": "1,290,000,000",
"genres": ["Animation","Adventure"],
"releaseDate": "2013-11-27",
"actors": ["Kristen Bell","Idina Menzel","Josh Gad","Jonathan Groff"],
"director": "Chris Buck",
"author": "Jennifer Lee"
},

{
"id": 45,
"title": "Moana",
"trailerURL": "https://youtu.be/LKFuXETZUsI",
"posterURL": "https://image.tmdb.org/t/p/original/4JeeqYQ4yHId4sIOLoPp6tdn2.jpg",
"rating": 7.6,
"description": "A young Polynesian girl sets sail to restore the heart of a goddess and save her island.",
"budget": "150,000,000",
"revenue": "690,800,000",
"genres": ["Animation","Adventure"],
"releaseDate": "2016-11-23",
"actors": ["Auli'i Cravalho","Dwayne Johnson","Rachel House"],
"director": "Ron Clements",
"author": "Jared Bush"
},

{
"id": 46,
"title": "Inside Out",
"trailerURL": "https://youtu.be/seMwpP0yeu4",
"posterURL": "https://image.tmdb.org/t/p/original/lRHE0vzf3oYJrhbsHXjIkF4Tl5A.jpg",
"rating": 8.1,
"description": "The emotions inside a young girl's mind guide her through life changes.",
"budget": "175,000,000",
"revenue": "858,800,000",
"genres": ["Animation","Comedy"],
"releaseDate": "2015-06-19",
"actors": ["Amy Poehler","Bill Hader","Mindy Kaling","Phyllis Smith"],
"director": "Pete Docter",
"author": "Pete Docter"
},

{
"id": 47,
"title": "Coco",
"trailerURL": "https://youtu.be/Rvr68u6k5sI",
"posterURL": "https://image.tmdb.org/t/p/original/eKi8dIrr8voobbaGzDpe8w0PVbC.jpg",
"rating": 8.4,
"description": "A young boy journeys into the Land of the Dead to uncover his family's musical past.",
"budget": "175,000,000",
"revenue": "814,300,000",
"genres": ["Animation","Adventure"],
"releaseDate": "2017-11-22",
"actors": ["Anthony Gonzalez","Gael García Bernal","Benjamin Bratt"],
"director": "Lee Unkrich",
"author": "Adrian Molina"
},

{
"id": 48,
"title": "Up",
"trailerURL": "https://youtu.be/ORFWdXl_zJ4",
"posterURL": "https://image.tmdb.org/t/p/original/mFvoEwSfLqbcWwFsDjQebn9bzFe.jpg",
"rating": 8.2,
"description": "An elderly man ties thousands of balloons to his house and flies to South America with a young stowaway.",
"budget": "175,000,000",
"revenue": "735,100,000",
"genres": ["Animation","Adventure"],
"releaseDate": "2009-05-29",
"actors": ["Ed Asner","Jordan Nagai","Christopher Plummer"],
"director": "Pete Docter",
"author": "Pete Docter"
},

{
"id": 49,
"title": "Ratatouille",
"trailerURL": "https://youtu.be/NgsQ8mVkN8w",
"posterURL": "https://image.tmdb.org/t/p/original/t3vaWRPSf6WjDSamIkKDs1iQWna.jpg",
"rating": 8.1,
"description": "A rat with a passion for cooking forms an unlikely partnership with a young kitchen worker.",
"budget": "150,000,000",
"revenue": "623,726,000",
"genres": ["Animation","Comedy"],
"releaseDate": "2007-06-29",
"actors": ["Patton Oswalt","Ian Holm","Lou Romano"],
"director": "Brad Bird",
"author": "Brad Bird"
},

{
"id": 50,
"title": "Wall-E",
"trailerURL": "https://youtu.be/CZ1CATNbXg0",
"posterURL": "https://image.tmdb.org/t/p/original/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg",
"rating": 8.4,
"description": "A lonely robot tasked with cleaning Earth discovers love and inadvertently saves humanity.",
"budget": "180,000,000",
"revenue": "533,281,433",
"genres": ["Animation","Sci-Fi"],
"releaseDate": "2008-06-27",
"actors": ["Ben Burtt","Elissa Knight","Jeff Garlin"],
"director": "Andrew Stanton",
"author": "Andrew Stanton"
}

]
module.exports = movies
